[build]
  publish = "dist"
  command = "pnpm run build:netlify"

[context.production.environment]
  NODE_VERSION = "20"

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
