[build]
  publish = "dist"
  command = "pnpm run build:netlify"

[dev]
  port = 5173
  publish = "dist"
  targetPort = 5173

# Ensure SPA routing works properly (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
