[build]
  base = "apps/web"
  publish = "dist"
  command = "pnpm install && pnpm run build"

[context.production.environment]
  NODE_VERSION = "18"

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
