name: orca-app
region: nyc
features:
  - buildpack-stack=ubuntu-22
services:
- name: ezedit2025
  environment_slug: node-js
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 3000
  build_command: npm install && npm run build
  run_command: npm start
  source_dir: /
  github:
    repo: Swimhack/ezEdit2025
    branch: main
    deploy_on_push: true
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: NODE_VERSION
    value: "20"
    scope: BUILD_TIME
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: "https://natjhcqynqziccssnwim.supabase.co"
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdGpoY3F5bnF6aWNjc3Nud2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE5NjY0NTAsImV4cCI6MjAyNzU0MjQ1MH0.5WJUTcFAG3AH_7vYG7TgfZsZ16DLrgugWWloacJdL0I"
    scope: BUILD_TIME
  - key: AI_AGENT_MODE
    value: production
    scope: BUILD_TIME
  - key: ENABLE_OPERATOR
    value: "true"
    scope: BUILD_TIME
  - key: OPENAI_API_KEY
    value: "your-openai-key-here"
    scope: RUN_TIME
  - key: ANTHROPIC_API_KEY
    value: "your-anthropic-key-here"
    scope: RUN_TIME
ingress:
  rules:
    - match:
        path:
          prefix: /
        authority:
          exact: ''
      component:
        name: ezedit2025
domains:
  - domain: ezedit.co
    type: PRIMARY
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED