name: ezedit
static_sites:
- name: ezedit
  github:
    repo: Swimhack/ezEdit-1
    branch: main
    deploy_on_push: true
  source_dir: /
  output_dir: /
  build_command: ""
  environment_slug: html
  routes:
  - path: /
  envs: []
  cors:
    allow_origins:
    - regex: .*
    allow_methods:
    - GET
    - OPTIONS
    - HEAD
