name: EzEdit Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  build-frontend:
    name: Build & Deploy Front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: ppnpm install --no-frozen-lockfile
      - name: Lint & Test
        run: |
          pnpm run lint
          pnpm run test
      - name: Build Vite app
        run: pnpm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist
          production-branch: main
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id:   ${{ secrets.NETLIFY_SITE_ID }}
        if: github.ref == 'refs/heads/main'

  publish-worker:
    name: Publish Cloudflare Worker
    needs: build-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler@3
      - name: Publish Worker
        run: wrangler publish --minify
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  supabase-migrate:
    name: Supabase Migrations
    needs: publish-worker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Supabase CLI
        run: npm install -g supabase
      - name: Push Schema
        run: supabase db push --non-interactive
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID:  ${{ secrets.SUPABASE_PROJECT_ID }}
